# Generated by Django 2.2 on 2020-03-31 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('news_title', models.CharField(blank=True, default='', max_length=200, verbose_name='新闻标题')),
                ('news_type', models.CharField(blank=True, default='', max_length=50, verbose_name='新闻类型')),
                ('news_time', models.CharField(blank=True, default='', max_length=50, verbose_name='发布日期')),
                ('news_content', models.TextField(blank=True, default='', verbose_name='新闻内容')),
                ('news_url', models.URLField(blank=True, default='', verbose_name='新闻链接')),
            ],
            options={
                'verbose_name': '新闻系统',
                'verbose_name_plural': '新闻系统',
            },
        ),
    ]
