# Generated by Django 2.2 on 2020-03-31 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('year', models.CharField(blank=True, default='', max_length=100, verbose_name='学年')),
                ('semester', models.IntegerField(blank=True, null=True, verbose_name='学期')),
                ('course_title', models.CharField(blank=True, default='', max_length=100, verbose_name='课程名称')),
                ('weeks', models.CharField(blank=True, default='', max_length=50, verbose_name='周数')),
                ('campus', models.CharField(blank=True, default='', max_length=50, verbose_name='校区')),
                ('place_class', models.CharField(blank=True, default='', max_length=50, verbose_name='上课地点')),
                ('teacher', models.CharField(blank=True, default='', max_length=50, verbose_name='教师')),
                ('teaching_class', models.CharField(blank=True, default='', max_length=50, verbose_name='教学班')),
                ('assessment_method', models.CharField(blank=True, default='', max_length=50, verbose_name='考核方式')),
                ('course_hours', models.CharField(blank=True, default='', max_length=50, verbose_name='课程学时组成')),
                ('week_hours', models.CharField(blank=True, default='', max_length=50, verbose_name='周学时')),
                ('total_hours', models.CharField(blank=True, default='', max_length=50, verbose_name='总学时')),
                ('credit', models.CharField(blank=True, default='', max_length=50, verbose_name='学分')),
            ],
            options={
                'verbose_name': '课表系统',
                'verbose_name_plural': '课表系统',
            },
        ),
    ]
